-- Seeding table project
INSERT INTO "project" ("id", "created_at", "title", "description", "sector", "lead_agency", "participating_agencies", "location_lat", "location_lon", "location_object", "type", "funding", "start_date", "current_status", "sponsor", "sponsor_contact", "parent_project_id", "location_text", "other") VALUES (1, '2025-02-19T14:12:43.935047+00:00', 'Generic Infrastructure Project  ', 'This project will build an infrastructure component. ', 'Infrastructure  ', 'Agency A', 'Agency B  ', 38.8998620437023, -7703813253558240, NULL, 'Infrastructure, Buildings', 'Grant 1245 $1M  ', '2025-03-01', 'Pre-application', 'Company A', NULL, NULL, NULL, NULL);

-- Seeding table process_instance
INSERT INTO "process_instance" ("id", "parent_project_id", "created_at", "parent_process_id", "agency_id", "federal_id", "type", "status", "stage", "start_date", "complete_date", "outcome", "comment_start", "comment_end", "lead_agency", "joint_lead_agency", "cooperating_agencies", "participating_agencies", "notes", "process_model", "other", "purpose_need", "description") VALUES (1, 1, '2025-02-19T14:14:32.187135+00:00', NULL, 'AAA-123 ', 'EISX-000-00-000-1739960554', 'EIS', 'Complete', NULL, '2025-03-01', '2025-05-10', 'Approved', NULL, NULL, 'Agency A', 'Agency B ', 'Agency C', NULL, NULL, NULL, NULL, NULL, NULL);

-- Seeding table document
INSERT INTO "document" ("id", "created_at", "parent_process_id", "related_document_id", "title", "volume_title", "document_revision", "revision_no", "supplement_no", "publish_date", "prepared_by", "status", "public_access", "url", "notes", "document_summary", "document_toc", "document_type", "other") VALUES (1, '2025-02-19T14:18:19.070403+00:00', 1, NULL, 'Project NOI', NULL, 'N/A', NULL, NULL, '2025-03-01', 'FAA', 'Complete', TRUE, NULL, NULL, NULL, NULL, 'NOI', NULL);
INSERT INTO "document" ("id", "created_at", "parent_process_id", "related_document_id", "title", "volume_title", "document_revision", "revision_no", "supplement_no", "publish_date", "prepared_by", "status", "public_access", "url", "notes", "document_summary", "document_toc", "document_type", "other") VALUES (3, '2025-02-19T14:20:03.422395+00:00', 1, 2, 'Project FEIS', 'Volume 1: Whole thing', NULL, NULL, NULL, '2025-05-01', 'FAA', 'Complete', TRUE, NULL, NULL, NULL, NULL, 'FEIS', NULL);

-- Seeding table engagement
INSERT INTO "engagement" ("id", "created_at", "parent_process_id", "type", "location", "related_document_id", "attendance", "participation", "notes", "start_datetime", "end_datetime", "other") VALUES (1, '2025-02-19T14:43:25.98391+00:00', 1, 'Public Comment Period', NULL, 1, NULL, NULL, NULL, '2025-04-01T13:43:04+00:00', '2025-04-10T13:43:16+00:00', NULL);

-- Seeding table case_event
INSERT INTO "case_event" ("id", "created_at", "parent_process_id", "parent_event_id", "related_document_id", "name", "description", "source", "type", "public_access", "tier", "status", "outcome", "assigned_entity", "datetime", "following_segment_name", "related_engagement_id", "other") VALUES (1, '2025-02-19T14:35:08.738838+00:00', 1, NULL, 1, 'NOI published', 'NOI published in federal register', NULL, 'NOI', TRUE, 1, 'Completed', NULL, 'FAA', '2025-03-01T17:00:00+00:00', 'Scoping', NULL, NULL);
INSERT INTO "case_event" ("id", "created_at", "parent_process_id", "parent_event_id", "related_document_id", "name", "description", "source", "type", "public_access", "tier", "status", "outcome", "assigned_entity", "datetime", "following_segment_name", "related_engagement_id", "other") VALUES (2, '2025-02-19T14:36:39.960579+00:00', 1, NULL, NULL, 'Scoping complete', 'Scoping finished', NULL, '', TRUE, 2, 'Complete', NULL, 'FAA', '2025-03-12T16:00:00+00:00', 'Drafting', NULL, NULL);
INSERT INTO "case_event" ("id", "created_at", "parent_process_id", "parent_event_id", "related_document_id", "name", "description", "source", "type", "public_access", "tier", "status", "outcome", "assigned_entity", "datetime", "following_segment_name", "related_engagement_id", "other") VALUES (5, '2025-02-19T14:41:43.002079+00:00', 1, NULL, 3, 'NOA of FEIS', 'Notice of Availability of FEIS', NULL, 'FEIS', TRUE, 1, 'Completed', 'Approved', NULL, '2025-05-01T16:00:00+00:00', 'ROD prep', NULL, NULL);
INSERT INTO "case_event" ("id", "created_at", "parent_process_id", "parent_event_id", "related_document_id", "name", "description", "source", "type", "public_access", "tier", "status", "outcome", "assigned_entity", "datetime", "following_segment_name", "related_engagement_id", "other") VALUES (6, '2025-02-19T14:42:36.52262+00:00', 1, NULL, NULL, 'ROD published', 'Record of Decision Published', NULL, 'ROD', TRUE, 1, 'Complete', NULL, NULL, '2025-05-07T16:00:00+00:00', NULL, NULL, NULL);
INSERT INTO "case_event" ("id", "created_at", "parent_process_id", "parent_event_id", "related_document_id", "name", "description", "source", "type", "public_access", "tier", "status", "outcome", "assigned_entity", "datetime", "following_segment_name", "related_engagement_id", "other") VALUES (4, '2025-02-19T14:40:01.424102+00:00', 1, NULL, NULL, 'Comment Period Close', 'Public comment period closed', NULL, NULL, TRUE, 2, 'Complete', NULL, 'FAA', '2025-04-10T16:00:00+00:00', 'Complete FEIS', 1, NULL);

-- Seeding table process_model
INSERT INTO "process_model" ("id", "created_at", "title", "description", "notes", "bpmn_model", "legal_structure_id", "legal_structure_text", "screening_description", "screening_desc_json", "agency", "parent_model", "DMN_model", "other") VALUES (1, '2025-03-13T15:40:46.102397+00:00', 'DOE Training CE Screening', 'This process model screens for a generic set of conditions that could classify a project as a CE. ', NULL, NULL, NULL, 'CFR Reference', 'There shouldn''t be any extraordinary circumstances and there are conditions that are integral to the thing.  ', NULL, 'DOE', NULL, NULL, NULL);

-- Seeding table legal_structure
INSERT INTO "legal_structure" ("id", "created_at", "title", "citation", "description", "context", "issuing_authority", "effective_date", "compliance_data", "url", "other") VALUES (1, '2025-05-06T16:59:55.27139+00:00', 'Agency Categorical Exclusions', '24 CFR 58.35', 'Categorical exclusion refers to a category of activities for which no environmental impact statement or environmental assessment and finding of no significant impact under NEPA is required, except in extraordinary circumstances (see § 58.2(a)(3)) in which a normally excluded activity may have a significant impact. Compliance with the other applicable Federal environmental laws and authorities listed in § 58.5 is required for any categorical exclusion listed in paragraph (a) of this section.', NULL, 'HUD', NULL, NULL, 'https://www.ecfr.gov/current/title-24/section-58.35', NULL);

-- Seeding table decision_element
INSERT INTO "decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other") VALUES (1, '2025-03-13T15:42:28.261684+00:00', 1, NULL, 'Action class', 'Training exercises and simulations (including, but not limited to, firing-range training, small-scale and short-duration force-on-force exercises, emergency response training, fire fighter and rescue training, and decontamination and spill cleanup training) conducted under appropriately controlled conditions and in accordance with applicable requirements.', 'Binary', 1, FALSE, FALSE, NULL, 'Is this a the thing described?', 'Yes/no', NULL, 'Check if yes', NULL, 'Core', NULL, NULL, NULL);

-- Seeding table process_decision_payload
INSERT INTO "process_decision_payload" ("id", "created_at", "process_decision_element", "process", "project", "data_description", "evaluation_data", "response", "result", "result_bool", "result_notes", "result_data", "result_source", "parent_payload", "other", "data_annotation", "evaluation_data_annotation") VALUES (1, '2025-05-06T17:13:05.063297+00:00', 1, 1, 1, 'project description', '[{"id":1,"type":"Infrastructure, Buildings","other":null,"title":"Generic Infrastructure Project  ","sector":"Infrastructure  ","funding":"Grant 1245 $1M  ","sponsor":"Company A","created_at":"2025-02-19T14:12:43.935047+00:00","start_date":"2025-03-01","description":"This project will build an infrastructure component. ","lead_agency":"Agency A","location_lat":38.8998620437023,"location_lon":-7703813253558240,"location_text":null,"current_status":"Pre-application","location_object":null,"sponsor_contact":null,"parent_project_id":null,"participating_agencies":"Agency B  "}]'::json, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "process_decision_payload" ("id", "created_at", "process_decision_element", "process", "project", "data_description", "evaluation_data", "response", "result", "result_bool", "result_notes", "result_data", "result_source", "parent_payload", "other", "data_annotation", "evaluation_data_annotation") VALUES (2, '2025-05-06T17:14:42.525282+00:00', 1, 1, 1, 'Project description', '[{"id":1,"type":"Infrastructure, Buildings","other":null,"title":"Generic Infrastructure Project  ","sector":"Infrastructure  ","funding":"Grant 1245 $1M  ","sponsor":"Company A","created_at":"2025-02-19T14:12:43.935047+00:00","start_date":"2025-03-01","description":"This project will build an infrastructure component. ","lead_agency":"Agency A","location_lat":38.8998620437023,"location_lon":-7703813253558240,"location_text":null,"current_status":"Pre-application","location_object":null,"sponsor_contact":null,"parent_project_id":null,"participating_agencies":"Agency B  "}]'::json, 'Approved', 'Success', TRUE, 'EIS approved', NULL, 'Process model business rules', 1, NULL, NULL, NULL);

-- Seeding table comment
INSERT INTO "comment" ("id", "created_at", "parent_document_id", "commenter_entity", "date_submitted", "submission_method", "content_text", "content_json", "response_text", "response_json", "public_source", "public_acess", "other") VALUES (1, '2025-02-19T14:44:14.179487+00:00', 1, 'Alice', '2025-04-02', 'Federal Register', 'I love this!', NULL, 'Thanks for your input.   ', NULL, TRUE, FALSE, NULL);
INSERT INTO "comment" ("id", "created_at", "parent_document_id", "commenter_entity", "date_submitted", "submission_method", "content_text", "content_json", "response_text", "response_json", "public_source", "public_acess", "other") VALUES (2, '2025-02-19T14:45:38.29017+00:00', 1, 'Ben', '2025-04-05', 'Regulations.gov', 'I am worried. ', NULL, 'Thanks for your input.   ', NULL, TRUE, FALSE, NULL);

-- Seeding table gis_data
INSERT INTO "gis_data" ("id", "created_at", "parent_project_id", "parent_process_id", "parent_document_id", "parent_case_event_id", "parent_comment_id", "parent_engagement_id", "description", "extent", "centroid_lat", "centroid_lon", "creator", "creator_contact", "notes", "container_inventory", "map_image", "data_container", "address", "updated_last", "other") VALUES (1, '2025-02-19T14:22:22.749759+00:00', 1, NULL, NULL, NULL, NULL, NULL, 'Project location', NULL, 38.8997743722264, -77.0381379, 'Dave', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Seeding table gis_data_element
INSERT INTO "gis_data_element" ("id", "created_at", "parent_gis", "container_reference", "format", "access_method", "coordinate_system", "top_left_lat", "top_left_lon", "bot_right_lat", "bot_right_lon", "purpose", "data_match", "access_info", "other") VALUES (1, '2025-05-02T13:54:53.909398+00:00', 1, 'Centroid', 'Lat/Lon Pair', NULL, 'WGS84', NULL, NULL, NULL, NULL, 'Bespoke GIS Data', NULL, NULL, NULL);

